# https://hub.docker.com/_/postgres/
postgres:
  image: postgres:9-alpine # Latest 9.x 
  volumes:
    - "../:/brapi-dataset"
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
  command:
    - /brapi-dataset/docker/postgres/container-init.sh
